sonar.projectKey=mon-projet-react-node
sonar.projectName=Mon Projet React Node
sonar.sources=frontend/src,backend/src
sonar.tests=frontend/src,backend/src
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info,backend/cover
age/lcov.info
sonar.sourceEncoding=UTF-8